server:
  port: 8101

kafka:
  bootstrap-servers: 127.0.0.1:9092
  auto-offset-reset: earliest
  session-timeout-ms: 60000
  enable-auto-commit: true
  auto-commit-interval-ms: 500
  poll-timeout: 5000
  acks: all
  retries: 0
  linger-ms: 1
  batch-size: 16384
  buffer-memory: 33554432
  group-id: kafka-group-id
  input-topic: kafka-topic-name
  concurrency: 3
  max-poll-records: 350

